"""Initial migration.

Revision ID: 854962f23bce
Revises: 
Create Date: 2025-11-17 06:49:39.122890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854962f23bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('slug'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)

    # ### end Alembic commands ###
