"""Initial migration.

Revision ID: fdad66d37bac
Revises: 
Create Date: 2025-07-07 00:51:31.040814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdad66d37bac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_presets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('use_case', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('content', 'image', 'design', 'audio', 'video', 'other'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('frequency_penalty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('use_case')
    )
    op.create_table('options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('option_key', sa.String(length=150), nullable=False),
    sa.Column('option_value', sa.Text(), nullable=False),
    sa.Column('autoload', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_key')
    )
    op.create_table('terms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'author', 'subscriber'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('openai', 'gemini', 'anthropic', 'huggingface'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('ai_preset_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('preset_id', sa.BigInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('autocomplete', sa.Boolean(), nullable=True),
    sa.Column('summarize', sa.Boolean(), nullable=True),
    sa.Column('translate', sa.Boolean(), nullable=True),
    sa.Column('multi_chat', sa.Boolean(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['ai_presets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('publish', 'draft', 'pending', 'private', 'trash'), nullable=False),
    sa.Column('type', sa.Enum('post', 'page'), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('term_taxonomy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('taxonomy', sa.Enum('category', 'tag'), nullable=False),
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['term_taxonomy.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_meta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('meta_key', sa.String(length=50), nullable=True),
    sa.Column('meta_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meta_key', name='uq_user_meta')
    )
    op.create_table('ai_config_presets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.BigInteger(), nullable=False),
    sa.Column('preset_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['ai_configs.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['ai_presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_term_relationships',
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('term_taxonomy_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_taxonomy_id'], ['term_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id', 'term_taxonomy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_term_relationships')
    op.drop_table('ai_config_presets')
    op.drop_table('user_meta')
    op.drop_table('term_taxonomy')
    op.drop_table('posts')
    op.drop_table('ai_preset_features')
    op.drop_table('ai_configs')
    op.drop_table('users')
    op.drop_table('terms')
    op.drop_table('options')
    op.drop_table('ai_presets')
    # ### end Alembic commands ###
